api/urls.py
from django.urls import path

urlpatterns = [
]

deepconnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tinder.urls')),
    path('api/', include('api.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.template.defaultfilters import slugify
from phone_field import PhoneField
from django.contrib.auth.models import Group, Permission
from django.utils.text import slugify


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, username, phone, password, **extra_fields):
        values = [email, username, phone]
        field_value_map = dict(zip(self.model.REQUIRED_FIELDS, values))
        for field_name, value in field_value_map.items():
            if not value:
                raise ValueError('The {} value must be set'.format(field_name))

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            username=username,
            phone=phone,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_active', False)
        return self._create_user(email, username, phone, password, **extra_fields)

    def create_superuser(self, email, username, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, username, phone, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(unique=True, max_length=150, blank=True)
    name = models.CharField(max_length=150)
    lastname = models.CharField(max_length=150, blank=True, null=True, default='')
    phone = PhoneField(unique=True)
    date_of_birth = models.DateField(blank=True, null=True)
    picture = models.ImageField(blank=True, null=True, upload_to='ava')
    
    description = models.CharField(max_length=100)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(null=True)
    
    # wefwefwef
    SEX_CHOICES = {
        'Female' : 'Female',
        'Male' : 'Male'
    }
    sex = models.CharField(choices=SEX_CHOICES ,max_length=10)
    
    SOCIAL_OREINTATION = {
        'Extrovert' : 'Extrovert',
        'Ambivert' : 'Ambivert',
        'Introvert' : 'Introvert'
    }
    social_orientation = models.CharField(choices=SOCIAL_OREINTATION, max_length=50)
    agreeableness = models.PositiveIntegerField(default=50)
    emotional_stablility = models.PositiveIntegerField(default=50)
    # wefoinweofne
    
    groups = models.ManyToManyField(Group, related_name="custom_user_set", blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name="custom_user_permissions_set", blank=True)

    slug = models.SlugField()
    
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone', 'username']

    def get_full_name(self):
        return f'{self.name} {self.lastname}'

    def get_short_name(self):
        return self.name


    def save(self, *args, **kwargs):
        if not self.id and not self.slug:
            self.slug = slugify(self.username)
        super(User, self).save(*args, **kwargs)
        
    def __str__(self):
        return f'{self.name} {self.lastname}'
    
    

templates/page/login.html
<div class="tab-pane fade show active" id="login" role="tabpanel" aria-labelledby="login-tab"
    style="background-color: white !important;">
    <div class="d-flex align-items-center h-100 px-5 ms-xl-4 pt-2 pt-xl-0 mt-xl-n5">

        <form action="{% url 'signin' %}" method="POST" style="width: 23rem;">
            {% csrf_token %}

            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Log in</h3>

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="email" required>Email address</label>
                <input type="text" name="username" id="email" class="form-control form-control-lg" />
            </div>

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="password" required>Password</label>
                <input type="password" name="password" id="password" class="form-control form-control-lg" />
            </div>

            <div class="pt-1 mb-4">
                <button data-mdb-button-init data-mdb-ripple-init class="btn btn-info btn-lg btn-block"
                    type="submit">Login</button>
            </div>

        </form>

    </div>
</div>

templates/page/register.html
{% load static %}
<div class="tab-pane fade show" id="register" role="tabpanel" aria-labelledby="register-tab"
    style="background-color: white !important;">
    <form action="{% url 'signup' %}" method="POST" class="mt-5 mb-5 pb-5">
    {% csrf_token %}
    <div class="d-flex justify-content-center align-items-center overflow-auto px-5 ms-xl-4 pt-2 pt-xl-0 mt-xl-n5" style="width: 100%; height: auto; margin: 0 auto;">
            <div class="mt-5 mb-5 pb-5">

                <h3 class="fw-normal mb-4" style="letter-spacing: 1px;">Register</h3>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="email_reg" required>Email address</label>
                    <input type="email" name="email" id="email_reg" class="form-control form-control-lg required_forms_controls" required/>
                </div>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="username" required>Username:</label>
                    <input type="text" name="username" id="username" class="form-control form-control-lg required_forms_controls" required/>
                </div>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="name" required>Name:</label>
                    <input type="text" name="name" id="name" class="form-control form-control-lg required_forms_controls" required/>
                </div>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="lastname" required>Lastname:</label>
                    <input type="text" name="lastname" id="lastname" class="form-control form-control-lg required_forms_controls" required/>
                </div>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="phone" required>Phone:</label>
                    <input type="text" name="phone_0" id="phone" size="13" class="form-control form-control-lg required_forms_controls" required/>
                </div>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="id_date_of_birth" required>Date of birth:</label>
                    <input type="date" name="date_of_birth" id="id_date_of_birth" class="form-control form-control-lg required_forms_controls" required/>
                </div>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="id_password1" required>Password</label>
                    <input type="password" name="password1" id="id_password1" class="form-control form-control-lg required_forms_controls" autocomplete="new-password" required/>
                </div>
                <ul>
                    <li>Your password can’t be too similar to your other personal information.</li>
                    <li>Your password must contain at least 8 characters.</li>
                    <li>Your password can’t be a commonly used password.</li>
                    <li>Your password can’t be entirely numeric.</li>
                </ul>
                <div data-mdb-input-init class="form-outline mb-4">
                    <label class="form-label" for="id_password2" required>Password</label>
                    <input type="password" name="password2" id="id_password2" class="form-control form-control-lg required_forms_controls" aria-describedby="id_password2_helptext" autocomplete="new-password" required/>
                    <span class="helptext" id="id_password2_helptext">Enter the same password as before, for verification.</span>
                </div>
                <div class="pt-1">
                    <div  id="next_btn" class="btn btn-info btn-lg btn-block">Next</div>
                </div>
                
            </div>
        </div>
        {% include 'modal/profile_creation.html' %}
    </form>
</div>